language: java
dist: xenial
jdk: openjdk15
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
token: 
  secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache
