language: java
dist: xenial
jdk: openjdk15
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
token: $SONAR_TOKEN
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - "$HOME/.m2"
    - "$home/.sonar/cache"
